import {
  DEPARTMENTS,
  PRIORITY,
  TEMPLATE_STATUS,
  MASTER_DATA_FIELD_TYPES as F,
} from '../core/constants/index.js';

/**
 * A leaner 8-stage alternative to the official 10-phase workflow in
 * `storeLaunchTemplate.js`. Kept so the app ships with more than one playbook
 * to choose from; the official template holds the `isDefault` flag.
 */
export const franchiseLaunchTemplate = {
  name: 'Franchise Outlet Launch',
  code: 'MR-FRANCHISE-LAUNCH',
  description:
    'End-to-end playbook to open a new Mystery Rooms outlet — site sourcing through soft launch.',
  category: 'Franchise Launch',
  icon: 'Rocket',
  color: '#6E45FF',
  status: TEMPLATE_STATUS.PUBLISHED,
  isDefault: false,
  tags: ['franchise', 'expansion', 'launch'],
  stages: [
    {
      key: 'sourcing',
      name: 'Site Sourcing',
      order: 0,
      color: '#6E45FF',
      slaDays: 10,
      ownerDepartment: DEPARTMENTS.EXPANSION,
      description: 'Engage brokers, gather site options and shortlist the strongest catchments.',
      masterDataSchema: [
        { key: 'broker_name', label: 'Primary Broker', type: F.TEXT, required: true, order: 0 },
        { key: 'broker_phone', label: 'Broker Contact', type: F.TEXT, order: 1 },
        { key: 'options_count', label: 'Options Received', type: F.NUMBER, order: 2 },
        { key: 'preferred_locality', label: 'Preferred Locality', type: F.TEXT, order: 3 },
      ],
      tasks: [
        { key: 'engage_brokers', title: 'Engage local brokers', order: 0, estimatedDays: 2, priority: PRIORITY.HIGH, department: DEPARTMENTS.EXPANSION },
        { key: 'collect_options', title: 'Collect site options', order: 1, estimatedDays: 4, department: DEPARTMENTS.EXPANSION },
        { key: 'shortlist', title: 'Shortlist top 3 sites', order: 2, estimatedDays: 2, priority: PRIORITY.HIGH, department: DEPARTMENTS.EXPANSION,
          checklist: [{ label: 'Locality footfall reviewed', required: true }, { label: 'Rent range within budget' }] },
        { key: 'prelim_footfall', title: 'Preliminary footfall study', order: 3, estimatedDays: 2, department: DEPARTMENTS.EXPANSION },
      ],
    },
    {
      key: 'inspection',
      name: 'Site Inspection',
      order: 1,
      color: '#14B8A6',
      slaDays: 7,
      ownerDepartment: DEPARTMENTS.EXPANSION,
      description: 'Physically inspect shortlisted sites against the launch scorecard.',
      masterDataSchema: [
        { key: 'carpet_area', label: 'Carpet Area (sq.ft)', type: F.NUMBER, required: true, order: 0 },
        { key: 'frontage_ft', label: 'Frontage (ft)', type: F.NUMBER, order: 1 },
        { key: 'floor', label: 'Floor', type: F.SELECT, options: ['Ground', 'First', 'Second', 'Basement'], order: 2 },
        { key: 'parking', label: 'Parking Available', type: F.BOOLEAN, order: 3 },
        { key: 'footfall_score', label: 'Footfall Score (1-10)', type: F.NUMBER, order: 4 },
        { key: 'competitor_nearby', label: 'Competitor Nearby', type: F.BOOLEAN, order: 5 },
      ],
      tasks: [
        { key: 'physical_inspection', title: 'Physical site inspection', order: 0, estimatedDays: 2, priority: PRIORITY.HIGH, department: DEPARTMENTS.EXPANSION },
        { key: 'structural_check', title: 'Structural & Vaastu check', order: 1, estimatedDays: 1, department: DEPARTMENTS.PROJECTS },
        { key: 'catchment', title: 'Footfall & catchment analysis', order: 2, estimatedDays: 2, department: DEPARTMENTS.EXPANSION },
        { key: 'utilities_check', title: 'Utilities & power load check', order: 3, estimatedDays: 1, department: DEPARTMENTS.PROJECTS },
        { key: 'scorecard', title: 'Complete inspection scorecard', order: 4, estimatedDays: 1, priority: PRIORITY.HIGH, department: DEPARTMENTS.EXPANSION,
          checklist: [{ label: 'Area meets minimum', required: true }, { label: 'Power load sufficient', required: true }, { label: 'Emergency exits present', required: true }] },
      ],
    },
    {
      key: 'negotiation',
      name: 'Negotiation & Deal',
      order: 2,
      color: '#F5A623',
      slaDays: 8,
      ownerDepartment: DEPARTMENTS.FINANCE,
      description: 'Negotiate commercials and secure internal approval for the site.',
      masterDataSchema: [
        { key: 'monthly_rent', label: 'Monthly Rent', type: F.CURRENCY, required: true, order: 0 },
        { key: 'security_deposit', label: 'Security Deposit', type: F.CURRENCY, order: 1 },
        { key: 'lockin_months', label: 'Lock-in (months)', type: F.NUMBER, order: 2 },
        { key: 'escalation_pct', label: 'Rent Escalation %', type: F.NUMBER, order: 3 },
        { key: 'brokerage', label: 'Brokerage Amount', type: F.CURRENCY, order: 4 },
      ],
      tasks: [
        { key: 'rate_negotiation', title: 'Rent & terms negotiation', order: 0, estimatedDays: 3, priority: PRIORITY.HIGH, department: DEPARTMENTS.EXPANSION },
        { key: 'commercials', title: 'Finalize commercials', order: 1, estimatedDays: 2, department: DEPARTMENTS.FINANCE },
        { key: 'landlord_check', title: 'Landlord background check', order: 2, estimatedDays: 2, department: DEPARTMENTS.LEGAL },
        { key: 'deal_approval', title: 'Internal deal approval', order: 3, estimatedDays: 1, priority: PRIORITY.CRITICAL, department: DEPARTMENTS.FINANCE },
      ],
    },
    {
      key: 'legal',
      name: 'Legal & Contract',
      order: 3,
      color: '#38BDF8',
      slaDays: 10,
      ownerDepartment: DEPARTMENTS.LEGAL,
      description: 'Draft, vet, and register the lease agreement.',
      masterDataSchema: [
        { key: 'agreement_type', label: 'Agreement Type', type: F.SELECT, options: ['Lease', 'Leave & License'], required: true, order: 0 },
        { key: 'agreement_start', label: 'Agreement Start Date', type: F.DATE, order: 1 },
        { key: 'tenure_years', label: 'Tenure (years)', type: F.NUMBER, order: 2 },
        { key: 'registration_done', label: 'Registration Done', type: F.BOOLEAN, order: 3 },
      ],
      tasks: [
        { key: 'draft_agreement', title: 'Draft lease agreement', order: 0, estimatedDays: 3, department: DEPARTMENTS.LEGAL },
        { key: 'due_diligence', title: 'Legal due diligence', order: 1, estimatedDays: 3, priority: PRIORITY.HIGH, department: DEPARTMENTS.LEGAL },
        { key: 'stamp_registration', title: 'Stamp duty & registration', order: 2, estimatedDays: 3, department: DEPARTMENTS.LEGAL },
        { key: 'signed_handover', title: 'Signed agreement handover', order: 3, estimatedDays: 1, priority: PRIORITY.HIGH, department: DEPARTMENTS.LEGAL },
      ],
    },
    {
      key: 'fitout',
      name: 'Design & Fit-out',
      order: 4,
      color: '#A855F7',
      slaDays: 30,
      ownerDepartment: DEPARTMENTS.PROJECTS,
      description: 'Design the theme, build the rooms, install games and props.',
      masterDataSchema: [
        { key: 'design_theme', label: 'Signature Theme', type: F.SELECT, options: ['Prison Break', 'Heist', 'Haunted', 'Da Vinci', 'Mixed'], required: true, order: 0 },
        { key: 'fitout_vendor', label: 'Fit-out Vendor', type: F.TEXT, order: 1 },
        { key: 'fitout_budget', label: 'Fit-out Budget', type: F.CURRENCY, order: 2 },
        { key: 'games_count', label: 'Game Rooms to Build', type: F.NUMBER, required: true, order: 3 },
      ],
      tasks: [
        { key: 'concept_design', title: 'Concept & layout design', order: 0, estimatedDays: 5, priority: PRIORITY.HIGH, department: DEPARTMENTS.PROJECTS },
        { key: 'vendor_selection', title: 'Fit-out vendor selection', order: 1, estimatedDays: 3, department: DEPARTMENTS.PROJECTS },
        { key: 'civil_work', title: 'Civil & interior work', order: 2, estimatedDays: 10, priority: PRIORITY.HIGH, department: DEPARTMENTS.PROJECTS },
        { key: 'game_construction', title: 'Game room construction', order: 3, estimatedDays: 7, department: DEPARTMENTS.PROJECTS },
        { key: 'props_install', title: 'Theme props & set installation', order: 4, estimatedDays: 4, department: DEPARTMENTS.PROJECTS },
        { key: 'electrical_av', title: 'Electrical, lighting & AV', order: 5, estimatedDays: 3, department: DEPARTMENTS.PROJECTS },
        { key: 'snagging', title: 'Snagging & handover', order: 6, estimatedDays: 2, priority: PRIORITY.HIGH, department: DEPARTMENTS.PROJECTS,
          checklist: [{ label: 'All puzzles tested', required: true }, { label: 'Safety audit passed', required: true }] },
      ],
    },
    {
      key: 'staffing',
      name: 'Staffing & HR',
      order: 5,
      color: '#F43F5E',
      slaDays: 14,
      ownerDepartment: DEPARTMENTS.HR,
      description: 'Hire and certify the outlet team.',
      masterDataSchema: [
        { key: 'gm_required', label: 'Game Masters Required', type: F.NUMBER, required: true, order: 0 },
        { key: 'manager_hired', label: 'Outlet Manager Hired', type: F.BOOLEAN, order: 1 },
        { key: 'training_done', label: 'Training Completed', type: F.BOOLEAN, order: 2 },
      ],
      tasks: [
        { key: 'hire_manager', title: 'Hire Outlet Manager', order: 0, estimatedDays: 5, priority: PRIORITY.HIGH, department: DEPARTMENTS.HR },
        { key: 'hire_gms', title: 'Hire Game Masters', order: 1, estimatedDays: 5, department: DEPARTMENTS.HR },
        { key: 'hire_frontdesk', title: 'Hire front-desk staff', order: 2, estimatedDays: 4, department: DEPARTMENTS.HR },
        { key: 'onboarding', title: 'Staff onboarding', order: 3, estimatedDays: 2, department: DEPARTMENTS.HR },
        { key: 'gm_training', title: 'Game-master training & certification', order: 4, estimatedDays: 3, priority: PRIORITY.HIGH, department: DEPARTMENTS.OPERATIONS },
      ],
    },
    {
      key: 'marketing',
      name: 'Marketing & Pre-Launch',
      order: 6,
      color: '#84CC16',
      slaDays: 12,
      ownerDepartment: DEPARTMENTS.MARKETING,
      description: 'Build local demand and fill the pre-launch booking calendar.',
      masterDataSchema: [
        { key: 'launch_date', label: 'Planned Launch Date', type: F.DATE, required: true, order: 0 },
        { key: 'ad_budget', label: 'Ad Budget', type: F.CURRENCY, order: 1 },
        { key: 'campaigns', label: 'Campaigns Planned', type: F.NUMBER, order: 2 },
      ],
      tasks: [
        { key: 'gmb_seo', title: 'Local SEO & Google Business listing', order: 0, estimatedDays: 3, department: DEPARTMENTS.MARKETING },
        { key: 'paid_ads', title: 'Paid ads plan & setup', order: 1, estimatedDays: 3, department: DEPARTMENTS.MARKETING },
        { key: 'influencers', title: 'Influencer & PR tie-ups', order: 2, estimatedDays: 4, department: DEPARTMENTS.MARKETING },
        { key: 'crm_flows', title: 'WhatsApp & CRM flows', order: 3, estimatedDays: 2, department: DEPARTMENTS.MARKETING },
        { key: 'prelaunch_bookings', title: 'Pre-launch bookings drive', order: 4, estimatedDays: 4, priority: PRIORITY.HIGH, department: DEPARTMENTS.MARKETING },
      ],
    },
    {
      key: 'launch',
      name: 'Soft Launch & Handover',
      order: 7,
      color: '#10B981',
      slaDays: 5,
      ownerDepartment: DEPARTMENTS.OPERATIONS,
      description: 'Trial runs, fixes, and go-live handover to operations.',
      masterDataSchema: [
        { key: 'trial_bookings', label: 'Trial Bookings', type: F.NUMBER, order: 0 },
        { key: 'go_live_date', label: 'Go-Live Date', type: F.DATE, required: true, order: 1 },
        { key: 'handover_signoff', label: 'Handover Sign-off', type: F.BOOLEAN, order: 2 },
      ],
      tasks: [
        { key: 'dry_runs', title: 'Trial & dry runs', order: 0, estimatedDays: 2, priority: PRIORITY.HIGH, department: DEPARTMENTS.OPERATIONS },
        { key: 'fix_bugs', title: 'Fix game bugs & tune difficulty', order: 1, estimatedDays: 1, department: DEPARTMENTS.OPERATIONS },
        { key: 'soft_launch', title: 'Soft-launch event', order: 2, estimatedDays: 1, priority: PRIORITY.HIGH, department: DEPARTMENTS.MARKETING },
        { key: 'ops_handover', title: 'Ops handover & go-live', order: 3, estimatedDays: 1, priority: PRIORITY.CRITICAL, department: DEPARTMENTS.OPERATIONS,
          checklist: [{ label: 'POS & booking system live', required: true }, { label: 'Staff rota published', required: true }, { label: 'Go-live sign-off', required: true }] },
      ],
    },
  ],
};

export default franchiseLaunchTemplate;
