/* eslint-disable no-console */
/**
 * Enterprise-scale demo seed — 150 properties cascading through the real
 * 10-phase pipeline, generated by calling the exact same service functions
 * (`projectService`, `recordService`) the live app itself calls, so every
 * eligibility gate, seq number, activity-log entry and decision-gated
 * stage-completion is produced by the real business logic, not re-implemented.
 *
 * Every generated Project is tagged with a `SEED-` code prefix so it can be
 * identified and removed independently later via destroySeedEnterpriseDemo.js
 * — it never touches Projects you built by hand. Users are upserted by email
 * (idempotent) and are NOT considered disposable — the destroy script leaves
 * them alone.
 *
 * Timestamps: the service layer always stamps `createdAt`/`decidedAt`/etc. as
 * "now". Immediately after each create/decide call this script backdates
 * those fields directly (a plain `updateOne`, bypassing the service) to a
 * date appropriate to the property's own simulated timeline, so a property
 * sitting in "Project Closure" reads as having taken months, not minutes.
 *
 * SAFE-ish by design (purely additive, tagged), but this is a real write to
 * your database and will take several minutes given real DB round-trips per
 * record. Run with a smaller PROPERTY_COUNT first if you want to sanity-check.
 *
 *   node src/seed/seedEnterpriseDemo.js
 *   PROPERTY_COUNT=10 node src/seed/seedEnterpriseDemo.js   # small test run
 */
import dayjs from 'dayjs';
import mongoose from 'mongoose';
import { connectDatabase, disconnectDatabase } from '../config/database.js';
import { User } from '../modules/auth/auth.model.js';
import { Template } from '../modules/pms/templates/template.model.js';
import { Project } from '../modules/pms/projects/project.model.js';
import { Record } from '../modules/pms/records/record.model.js';
import { Activity } from '../modules/pms/activity/activity.model.js';
import { projectService } from '../modules/pms/projects/project.service.js';
import { recordService } from '../modules/pms/records/record.service.js';
import { ROLES, DEPARTMENTS } from '../core/constants/index.js';
import {
  rand, pick, pickN, chance,
  randomFirmName, randomPhone,
  CITIES, randomLocality, fillSchemaValues, randomRemark,
} from './enterpriseDemoData.js';

const CODE_PREFIX = 'SEED-';
const DEFAULT_PASSWORD = 'Admin@123';
const STAGE_ORDER = ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10'];

// Real department enum values double as p5/p6/p7's assessmentType keys.
const DEPT_VALUES = new Set(Object.values(DEPARTMENTS));

// ---------------- Users roster ----------------
// Extends (never duplicates — upserted by email) seed.js's original roster.
const NEW_USERS = [
  { name: 'Vivek Malhotra', email: 'vivek.md@mysteryrooms.in', role: ROLES.MD, title: 'Managing Director', avatarColor: '#B45309' },
  { name: 'Anjali Kapoor', email: 'anjali.ceo@mysteryrooms.in', role: ROLES.EA, title: 'Executive Assistant', avatarColor: '#9333EA' },
  { name: 'Suresh Reddy', email: 'suresh.bh@mysteryrooms.in', role: ROLES.MANAGER, title: 'Business Head', avatarColor: '#0D9488' },
  { name: 'Ritu Chawla', email: 'ritu.legal@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.LEGAL, title: 'Legal Manager', avatarColor: '#2563EB' },
  { name: 'Manish Agarwal', email: 'manish.finance@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.FINANCE, title: 'Finance Manager', avatarColor: '#DC2626' },
  { name: 'Farhan Ali', email: 'farhan.it@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.IT, title: 'IT Manager', avatarColor: '#0EA5E9' },
  { name: 'Kavita Desai', email: 'kavita.marketing@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.MARKETING, title: 'Marketing Manager', avatarColor: '#DB2777' },
  { name: 'Deepak Verma', email: 'deepak.ops@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.OPERATIONS, title: 'Operations Manager', avatarColor: '#16A34A' },
  { name: 'Ramesh Iyer', email: 'ramesh.construction@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.CONSTRUCTION, title: 'Construction Manager', avatarColor: '#CA8A04' },
  { name: 'Meera Pillai', email: 'meera.interior@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.INTERIOR, title: 'Interior Manager', avatarColor: '#7C3AED' },
  { name: 'Ashok Bhatia', email: 'ashok.procurement@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.PROCUREMENT, title: 'Procurement Manager', avatarColor: '#EA580C' },
  { name: 'Tarun Mehta', email: 'tarun.automation@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.AUTOMATION, title: 'Automation Manager', avatarColor: '#4F46E5' },
  { name: 'Nikhil Joshi', email: 'nikhil.store@mysteryrooms.in', role: ROLES.MANAGER, department: DEPARTMENTS.OPERATIONS, title: 'Store Manager', avatarColor: '#059669' },
  // Extra doers — one per department not already covered by seed.js's roster.
  { name: 'Aditi Rao', email: 'aditi.doer@mysteryrooms.in', role: ROLES.EMPLOYEE, department: DEPARTMENTS.CONSTRUCTION, employeeId: 'emp-con-003x', title: 'Site Supervisor', avatarColor: '#65A30D' },
  { name: 'Vikram Chauhan', email: 'vikram.doer@mysteryrooms.in', role: ROLES.EMPLOYEE, department: DEPARTMENTS.INTERIOR, employeeId: 'emp-int-004x', title: 'Interior Coordinator', avatarColor: '#C026D3' },
  { name: 'Shreya Bose', email: 'shreya.doer@mysteryrooms.in', role: ROLES.EMPLOYEE, department: DEPARTMENTS.PROCUREMENT, employeeId: 'emp-pro-003x', title: 'Procurement Associate', avatarColor: '#0891B2' },
  { name: 'Rajesh Trivedi', email: 'rajesh.doer@mysteryrooms.in', role: ROLES.EMPLOYEE, department: DEPARTMENTS.AUTOMATION, employeeId: 'emp-aut-003x', title: 'Automation Technician', avatarColor: '#4338CA' },
  { name: 'Nisha Saxena', email: 'nisha.doer@mysteryrooms.in', role: ROLES.EMPLOYEE, department: DEPARTMENTS.IT, employeeId: 'emp-it-003x', title: 'IT Support Executive', avatarColor: '#0284C7' },
  { name: 'Amit Khanna', email: 'amit.doer@mysteryrooms.in', role: ROLES.EMPLOYEE, department: DEPARTMENTS.LEGAL, employeeId: 'emp-leg-004x', title: 'Legal Executive', avatarColor: '#1D4ED8' },
];

// ---------------- Workflow distribution (approved plan: 150, +1 to Draft vs. the listed 149) ----------------
const BUCKETS = [
  { key: 'draft', count: 41, label: 'Draft' },
  { key: 'under_review', count: 20, label: 'Under Review' },
  { key: 'shortlisted', count: 35, label: 'Shortlisted' },
  { key: 'site_evaluation', count: 25, label: 'Site Evaluation' },
  { key: 'commercial_finalization', count: 12, label: 'Commercial Finalization' },
  { key: 'project_creation', count: 8, label: 'Project Creation' },
  { key: 'department_planning', count: 5, label: 'Department Planning' },
  { key: 'execution', count: 2, label: 'Execution' },
  { key: 'store_launch', count: 1, label: 'Store Launch' },
  { key: 'project_closure', count: 1, label: 'Project Closure' },
];
const PROPERTY_COUNT = Number(process.env.PROPERTY_COUNT) || BUCKETS.reduce((s, b) => s + b.count, 0);

/** Which stage a bucket's property currently sits AT (in-progress there); every stage before it is fully cleared. */
const BUCKET_CURRENT_STAGE = {
  draft: 'p1', under_review: 'p1', shortlisted: 'p1',
  site_evaluation: 'p2', commercial_finalization: 'p3', project_creation: 'p4',
  department_planning: 'p5', execution: 'p6', store_launch: 'p9', project_closure: 'p10',
};

function deptFromKey(key) {
  return DEPT_VALUES.has(key) ? key : null;
}

// ---------------- Small date helpers (for backdating) ----------------
function jitter(date, minDays, maxDays) {
  return dayjs(date).add(rand(minDays, maxDays), 'day').toDate();
}
function stageBaseDate(projectStart, stageKey) {
  const idx = STAGE_ORDER.indexOf(stageKey);
  return dayjs(projectStart).add(idx * 12 + rand(0, 4), 'day').toDate();
}

// NOTE: these go through `.collection.updateOne` (the raw MongoDB driver),
// not `Model.updateOne`. Record/Activity both declare `{ timestamps: true }`,
// and Mongoose's timestamps plugin silently strips `createdAt` from any
// query-level $set (createdAt is treated as set-once) while force-overwriting
// `updatedAt` to the real current time regardless of what's passed — so the
// obvious `Record.updateOne(..., {$set:{createdAt: date}})` looks like it
// works (modifiedCount: 1) but never actually moves the date. Going through
// `.collection` bypasses Mongoose's schema middleware entirely.
async function backdateRecordCreate(record, date) {
  const set = { createdAt: date, updatedAt: date };
  if (record.submittedAt) set.submittedAt = date;
  await Record.collection.updateOne({ _id: record._id }, { $set: set });
}
async function backdateRecordDecision(recordId, decision, date) {
  const set = { updatedAt: date, decidedAt: date };
  if (decision === 'approve') set.approvedAt = date;
  else if (decision === 'reject') set.rejectedAt = date;
  else if (decision === 'shortlist') set.shortlistedAt = date;
  await Record.collection.updateOne({ _id: recordId }, { $set: set });
}
async function backdateLatestActivity(entityId, date) {
  const latest = await Activity.findOne({ entityId }).sort({ createdAt: -1 });
  if (latest) await Activity.collection.updateOne({ _id: latest._id }, { $set: { createdAt: date } });
}
async function backdateStageCompletion(projectId, stageKey, date) {
  await Project.collection.updateOne(
    { _id: projectId, 'stages.key': stageKey },
    { $set: { 'stages.$.completedAt': date } },
  );
}

// ---------------- Users ----------------
async function upsertUsers() {
  const all = [];
  for (const u of NEW_USERS) {
    const doc = await User.findOneAndUpdate(
      { email: u.email },
      { $setOnInsert: { ...u, password: DEFAULT_PASSWORD } },
      { upsert: true, new: true },
    );
    all.push(doc);
  }
  // Pull in the existing seed.js roster too, so the demo has a full cast.
  const existing = await User.find({ email: { $nin: NEW_USERS.map((u) => u.email) } });
  all.push(...existing);

  const admin = all.find((u) => u.email === 'admin@mysteryrooms.in') || all.find((u) => u.role === ROLES.MD);
  const seniorAdmins = all.filter((u) => u.role === ROLES.MD);
  const managers = all.filter((u) => u.role === ROLES.MANAGER);
  const doers = all.filter((u) => u.role === ROLES.EMPLOYEE);

  const byDeptManager = {};
  const byDeptDoer = {};
  for (const dept of Object.values(DEPARTMENTS)) {
    byDeptManager[dept] = managers.filter((u) => u.department === dept);
    byDeptDoer[dept] = doers.filter((u) => u.department === dept);
  }

  return { all, admin, seniorAdmins, managers, doers, byDeptManager, byDeptDoer };
}

function actorFor(typeKey, users) {
  const dept = deptFromKey(typeKey);
  const pool = (dept && users.byDeptDoer[dept]?.length ? users.byDeptDoer[dept] : null) || users.doers;
  return pick(pool.length ? pool : users.managers);
}
function approverFor(typeKey, users) {
  const dept = deptFromKey(typeKey);
  const pool = (dept && users.byDeptManager[dept]?.length ? users.byDeptManager[dept] : null) || users.managers;
  return pick(pool.length ? pool : users.seniorAdmins);
}

// ---------------- Record helpers (wrap recordService, then backdate) ----------------

async function createOne(project, stageKey, type, propertyId, actor, dateWindow, status, overrideValues = {}) {
  const { values, attachments } = fillSchemaValues(type.masterDataSchema, { dateWindow, cityHint: project.city });
  Object.assign(values, overrideValues);
  const record = await recordService.create(
    {
      projectId: project._id,
      stageKey,
      assessmentType: type.key,
      parentRecordId: propertyId,
      values,
      status,
      attachments,
    },
    actor._id,
  );
  const createdDate = jitter(dateWindow[0], 0, 3);
  await backdateRecordCreate(record, createdDate);
  await backdateLatestActivity(record._id, createdDate);
  return { record, createdDate };
}

async function decideOne(record, decision, actor, afterDate, reason, remarks) {
  await recordService.decide(record._id, decision, reason, actor._id, remarks);
  const decidedDate = jitter(afterDate, 1, 5);
  await backdateRecordDecision(record._id, decision, decidedDate);
  await backdateLatestActivity(record._id, decidedDate);
  return decidedDate;
}

/** One assessmentType, fully done — one Approved record per required sub-item (or just one, for ordinary types). */
async function completeType(project, stageKey, type, propertyId, users, dateWindow) {
  const subField = type.subKeyField && type.masterDataSchema.find((f) => f.key === type.subKeyField);
  const optionSets = subField ? subField.options.map((opt) => ({ [type.subKeyField]: opt })) : [{}];
  for (const override of optionSets) {
    const actor = actorFor(type.key, users);
    const { record, createdDate } = await createOne(project, stageKey, type, propertyId, actor, dateWindow, 'submitted', override);
    const approver = approverFor(type.key, users);
    await decideOne(record, 'approve', approver, createdDate);
  }
}

/** Fully clear an entire stage (every assessmentType done) and mark it completed — mirrors what the real app's own auto-complete effect does once every module is Approved. */
async function fullyCompleteStage(project, stageKey, propertyId, users, template, projectStart, adminUser) {
  const stage = template.stages.find((s) => s.key === stageKey);
  const types = stage.assessmentTypes || [];
  if (!types.length) return;
  const dateWindow = [stageBaseDate(projectStart, stageKey), dayjs(stageBaseDate(projectStart, stageKey)).add(10, 'day').toDate()];
  for (const type of types) {
    await completeType(project, stageKey, type, propertyId, users, dateWindow);
  }
  // Site Evaluation isn't finished by its assessments alone — the manager
  // then Approves the property itself on the dashboard, which re-issues
  // decide('shortlist') and stamps a fresh `decidedAt`. That second decision
  // is what marks the property approved at Phase 2 (see
  // isPropertyApprovedAtP2 in project.service.js), and completeStage('p2')
  // enforces it, so the seed has to perform the same real action rather than
  // leaving only the original Phase-1 shortlist behind.
  if (stageKey === 'p2') {
    const approvedAtP2 = jitter(dateWindow[1], 0, 2);
    await recordService.decide(propertyId, 'shortlist', undefined, pick(users.managers)._id);
    await backdateRecordDecision(propertyId, 'shortlist', approvedAtP2);
    await backdateLatestActivity(propertyId, approvedAtP2);
  }
  await projectService.completeStage(project._id, stageKey, adminUser._id);
  await backdateStageCompletion(project._id, stageKey, dateWindow[1]);
}

/** Leave a stage realistically "in progress" — a mix of approved/submitted/draft/rejected-then-resubmitted, never fully done (so it never auto-completes). */
async function partiallyWorkStage(project, stageKey, propertyId, users, template, projectStart) {
  const stage = template.stages.find((s) => s.key === stageKey);
  const types = stage.assessmentTypes || [];
  if (!types.length) return;
  const dateWindow = [stageBaseDate(projectStart, stageKey), dayjs(stageBaseDate(projectStart, stageKey)).add(14, 'day').toDate()];
  const shuffled = [...types].sort(() => Math.random() - 0.5);
  const approveCount = rand(0, Math.max(0, shuffled.length - 1)); // never every type — stage must stay "in progress"

  for (let i = 0; i < shuffled.length; i += 1) {
    const type = shuffled[i];
    const subField = type.subKeyField && type.masterDataSchema.find((f) => f.key === type.subKeyField);
    const optionSets = subField
      ? pickN(subField.options, rand(1, Math.max(1, subField.options.length - 1))).map((opt) => ({ [type.subKeyField]: opt }))
      : [{}];

    for (const override of optionSets) {
      const roll = i < approveCount ? 'approve' : chance(12) ? 'reject' : chance(55) ? 'submit' : 'draft';
      const actor = actorFor(type.key, users);
      const status = roll === 'draft' ? 'draft' : 'submitted';
      const { record, createdDate } = await createOne(project, stageKey, type, propertyId, actor, dateWindow, status, override);

      if (roll === 'approve') {
        const approver = approverFor(type.key, users);
        await decideOne(record, 'approve', approver, createdDate);
      } else if (roll === 'reject') {
        const approver = approverFor(type.key, users);
        const rejectedDate = await decideOne(record, 'reject', approver, createdDate, randomRemark(), chance(60) ? randomRemark() : undefined);
        // Unlimited resubmissions, never overwrite — file a fresh one, left awaiting decision.
        const { record: resubmit } = await createOne(project, stageKey, type, propertyId, actor, [rejectedDate, dayjs(rejectedDate).add(3, 'day').toDate()], 'submitted', override);
        void resubmit;
      }
      // 'submit' and 'draft' just leave the created record where it is.
    }
  }
}

// ---------------- One property, end to end ----------------

async function buildProperty(city, code, bucket, users, template, adminUser) {
  const bucketDepth = STAGE_ORDER.indexOf(BUCKET_CURRENT_STAGE[bucket.key]);
  // Deeper buckets started further in the past — a Project Closure property
  // has been "running" for months; a fresh Draft started days ago.
  const startOffset = -1 * (bucketDepth * rand(10, 18) + rand(0, 10));
  const plannedStartDate = dayjs().add(startOffset, 'day').toDate();

  const owner = pick(users.managers);
  const project = await projectService.create(
    {
      name: `${randomFirmName()} — ${randomLocality(city)}`,
      code,
      templateId: template._id,
      city,
      address: `${randomLocality(city)}, ${city}`,
      areaSqft: rand(800, 6000),
      owner: owner._id,
      members: pickN(users.all, 2).map((u) => u._id),
      plannedStartDate,
      budget: { planned: rand(2000000, 15000000), actual: 0 },
      broker: { name: randomFirmName(), phone: randomPhone(), commissionPct: rand(1, 3) },
      tags: ['seed-enterprise-demo', city.toLowerCase(), bucket.key],
    },
    adminUser._id,
  );

  // p1 property record — every bucket has one.
  const p1Schema = template.stages.find((s) => s.key === 'p1').masterDataSchema;
  const dateWindow0 = [plannedStartDate, dayjs(plannedStartDate).add(6, 'day').toDate()];
  const doer = actorFor('expansion', users);
  const p1Status = bucket.key === 'draft' ? 'draft' : 'submitted';
  const { values: p1Values, attachments: p1Attachments } = fillSchemaValues(p1Schema, { dateWindow: dateWindow0, cityHint: city });
  p1Values.property_name = project.name.split('—')[1]?.trim() || randomFirmName();
  p1Values.city = city;
  p1Values.locality = randomLocality(city);
  const p1Record = await recordService.create(
    { projectId: project._id, stageKey: 'p1', values: p1Values, status: p1Status, attachments: p1Attachments },
    doer._id,
  );
  const p1CreatedDate = jitter(dateWindow0[0], 0, 2);
  await backdateRecordCreate(p1Record, p1CreatedDate);
  await backdateLatestActivity(p1Record._id, p1CreatedDate);

  if (bucket.key !== 'draft' && bucket.key !== 'under_review') {
    const manager = pick(users.managers);
    const shortlistDate = jitter(p1CreatedDate, 1, 4);
    await recordService.decide(p1Record._id, 'shortlist', undefined, manager._id);
    await backdateRecordDecision(p1Record._id, 'shortlist', shortlistDate);
    await backdateLatestActivity(p1Record._id, shortlistDate);
  }

  // Every stage strictly before the bucket's current stage: fully cleared.
  const currentStage = BUCKET_CURRENT_STAGE[bucket.key];
  const currentIdx = STAGE_ORDER.indexOf(currentStage);
  for (let i = 1; i < currentIdx; i += 1) {
    const stageKey = STAGE_ORDER[i];
    // p6 (Execution) and p10 (Project Closure) aren't decision-gated in the
    // real app — they'd never be "strictly before" the current stage here
    // anyway given the bucket set, but guarded for safety.
    await fullyCompleteStage(project, stageKey, p1Record._id, users, template, plannedStartDate, adminUser);
  }

  // The bucket's own current stage: realistically in progress (p1-only
  // buckets have already done everything relevant above). Works the same
  // way whether or not the stage is decision-gated — p6/p10 just never get
  // a forced completion elsewhere in this function either way.
  if (currentIdx >= 1) {
    await partiallyWorkStage(project, currentStage, p1Record._id, users, template, plannedStartDate);
  }

  return { code, city, bucket: bucket.label };
}

// ---------------- Main ----------------

async function main() {
  await connectDatabase();
  console.log('\n== Enterprise demo seed ==');

  const template = await Template.findOne({ isDefault: true });
  if (!template) throw new Error('No default Template found — run the base `npm run seed` first.');

  const users = await upsertUsers();
  const adminUser = users.admin;
  if (!adminUser) throw new Error('No admin user found/created.');
  console.log(`Users ready: ${users.all.length} total (${users.seniorAdmins.length} admin, ${users.managers.length} manager, ${users.doers.length} executor)`);

  // Expand BUCKETS into a flat property plan (respects PROPERTY_COUNT/BUCKET_FILTER for test runs).
  let plan = BUCKETS.flatMap((b) => Array.from({ length: b.count }, () => b));
  if (process.env.BUCKET_FILTER) plan = plan.filter((b) => b.key === process.env.BUCKET_FILTER);
  plan = plan.slice(0, PROPERTY_COUNT);
  console.log(`Building ${plan.length} properties across ${CITIES.length} cities...\n`);

  // Resolve city + a globally-unique code for every planned property up
  // front (sequential, cheap) — continuing each city's counter from
  // whatever SEED- projects already exist in that city, so re-running the
  // script (or a BUCKET_FILTER/PROPERTY_COUNT test slice) never collides
  // with codes an earlier run already created.
  const cityCounters = {};
  for (const city of CITIES) {
    const cityCode = city.slice(0, 3).toUpperCase();
    // eslint-disable-next-line no-await-in-loop
    cityCounters[city] = await Project.countDocuments({ code: new RegExp(`^${CODE_PREFIX}${cityCode}-`) });
  }
  const assignments = plan.map((bucket, i) => {
    const city = CITIES[i % CITIES.length];
    cityCounters[city] += 1;
    const code = `${CODE_PREFIX}${city.slice(0, 3).toUpperCase()}-${String(cityCounters[city]).padStart(4, '0')}`;
    return { bucket, city, code };
  });

  const CONCURRENCY = 6;
  let done = 0;
  const results = [];
  for (let i = 0; i < assignments.length; i += CONCURRENCY) {
    const batch = assignments.slice(i, i + CONCURRENCY);
    const batchResults = await Promise.all(
      batch.map(({ bucket, city, code }) =>
        buildProperty(city, code, bucket, users, template, adminUser)
          .then((r) => {
            done += 1;
            console.log(`${String(done).padStart(3)}/${assignments.length}  ${r.code.padEnd(14)} ${r.city.padEnd(12)} -> ${r.bucket}`);
            return r;
          })
          .catch((err) => {
            done += 1;
            console.error(`${String(done).padStart(3)}/${assignments.length}  FAILED (${code}, ${bucket.label}): ${err.message}`);
            return null;
          }),
      ),
    );
    results.push(...batchResults);
  }

  const counts = {
    users: await User.countDocuments(),
    seedProjects: await Project.countDocuments({ code: new RegExp(`^${CODE_PREFIX}`) }),
    seedRecords: await Record.countDocuments({ project: { $in: (await Project.find({ code: new RegExp(`^${CODE_PREFIX}`) }).select('_id')).map((p) => p._id) } }),
    seedActivities: await Activity.countDocuments({ project: { $in: (await Project.find({ code: new RegExp(`^${CODE_PREFIX}`) }).select('_id')).map((p) => p._id) } }),
  };
  const failed = results.filter((r) => r === null).length;

  console.log('\n✅ Enterprise demo seed complete:', counts);
  if (failed) console.log(`⚠️  ${failed} propert${failed === 1 ? 'y' : 'ies'} failed — see errors above.`);
}

main()
  .catch((err) => {
    console.error('✖ Seed failed:', err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await disconnectDatabase();
    await mongoose.connection.close().catch(() => {});
    process.exit(process.exitCode || 0);
  });
